services:
  - type: web
    name: musictastematch
    runtime: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
