# ------- USING GOOGLE's GEMINI GENERATIVE-AI API TO INTEGRATE AI CAPABILITIES --------

import os
import time
from google import genai
from dotenv import load_dotenv

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))


def critique_recommendations(user_input: str, user_prefs: dict, recommendations: list, confidence: dict) -> str:
    """Use Gemini to review the recommendations and flag anything suspicious or misaligned."""

    rec_summary = "\n".join([
        f"- {song['title']} by {song['artist']} (genre: {song['genre']}, mood: {song['mood']}, score: {score:.2f})"
        for song, score, reasons in recommendations
    ])

    flags_summary = "\n".join(confidence["flags"]) if confidence["flags"] else "No flags detected."

    prompt = f"""You are a music recommendation quality reviewer for MusicTasteMatch 2.0.

A user described their music taste as: "{user_input}"

This was translated into the following preference profile:
- Preferred genre: {user_prefs['preferred_genre']}
- Preferred mood: {user_prefs['preferred_mood']}
- Target energy: {user_prefs['target_energy']}
- Target valence: {user_prefs['target_valence']}

The system recommended these songs:
{rec_summary}

The bias detector flagged the following issues:
{flags_summary}

Confidence score: {confidence['confidence_score']} out of 1.0

Please write a short 2-3 sentence critique of these recommendations. Be specific about:
1. Whether the recommendations seem aligned with what the user actually asked for
2. Any obvious mismatches you notice
3. One concrete suggestion for how the results could be improved

Be direct and honest."""

    # Retry up to 3 times on server errors
    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=prompt
            )
            return response.text.strip()
        except Exception as e:
            error_str = str(e)
            if "503" in error_str or "UNAVAILABLE" in error_str:
                if attempt < 2:
                    print(f"   ⚠️ Gemini busy, retrying in 5 seconds... (attempt {attempt + 1}/3)")
                    time.sleep(5)
                else:
                    return "AI critique temporarily unavailable — Gemini is experiencing high demand. Results above were generated by the scoring engine."
            elif "429" in error_str or "RESOURCE_EXHAUSTED" in error_str:
                return "AI critique unavailable — API quota exceeded. Results above were generated by the scoring engine."
            else:
                return f"AI critique unavailable — {error_str[:100]}"

    return "AI critique unavailable after 3 attempts."


def refine_preferences_from_critique(user_input: str, user_prefs: dict, critique_text: str) -> dict:
    """Use Gemini to extract preference adjustments from the critique and return updated prefs."""
    prompt = f"""You are helping refine a music recommendation preference profile.

Original user request: "{user_input}"

Current preference profile:
- preferred_genre: {user_prefs['preferred_genre']}
- preferred_mood: {user_prefs['preferred_mood']}
- target_energy: {user_prefs['target_energy']}
- target_valence: {user_prefs['target_valence']}
- target_tempo_bpm: {user_prefs['target_tempo_bpm']}

Critique of the current recommendations:
{critique_text}

Based ONLY on the critique, suggest specific adjustments to improve alignment.
Respond with ONLY a valid JSON object containing only the keys that need adjusting.
Valid keys: preferred_genre, preferred_mood, target_energy, target_valence, target_tempo_bpm, target_danceability, target_acousticness, target_instrumentalness, target_speechiness, target_liveness
Numeric values must be between 0.0 and 1.0 (except target_tempo_bpm which is 60-200).
If no adjustments are needed, respond with an empty JSON object: {{}}

Example response: {{"target_energy": 0.6, "target_valence": 0.4}}"""

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        text = response.text.strip()
        # Strip markdown code fences if present
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        import json
        adjustments = json.loads(text.strip())
        refined = {**user_prefs, **adjustments}
        return refined
    except Exception:
        return user_prefs


# ---------------- USING LLAMA TO INTEGRATE AI CAPABILITIES -----------------

# import ollama


# def critique_recommendations(user_input: str, user_prefs: dict, recommendations: list, confidence: dict) -> str:
#     """Use Llama 3.2 to review the recommendations and flag anything suspicious or misaligned."""

#     rec_summary = "\n".join([
#         f"- {song['title']} by {song['artist']} (genre: {song['genre']}, mood: {song['mood']}, score: {score:.2f})"
#         for song, score, reasons in recommendations
#     ])

#     flags_summary = "\n".join(confidence["flags"]) if confidence["flags"] else "No flags detected."

#     prompt = f"""You are a music recommendation quality reviewer for MusicTasteMatch 2.0.

# A user described their music taste as: "{user_input}"

# This was translated into the following preference profile:
# - Preferred genre: {user_prefs['preferred_genre']}
# - Preferred mood: {user_prefs['preferred_mood']}
# - Target energy: {user_prefs['target_energy']}
# - Target valence: {user_prefs['target_valence']}

# The system recommended these songs:
# {rec_summary}

# The bias detector flagged the following issues:
# {flags_summary}

# Confidence score: {confidence['confidence_score']} out of 1.0

# Please write a short 2-3 sentence critique of these recommendations. Be specific about:
# 1. Whether the recommendations seem aligned with what the user actually asked for
# 2. Any obvious mismatches you notice (wrong genre, wrong mood, wrong energy)
# 3. One concrete suggestion for how the results could be improved

# Be direct and honest. Do not be overly positive if the results are poor."""

#     response = ollama.chat(
#         model="llama3.2",
#         messages=[{"role": "user", "content": prompt}]
#     )

#     return response["message"]["content"].strip()